services:
  web:
    restart: always
    build: .
    links:
      - postgres:postgres

    environment:
      DEBUG: False
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "test_app"  #Введите название базы данных postgres
      DATABASE_PORT: "5432"
      POSTGRES_USER: "postgres"  #Введите название пользователя базы данных
      POSTGRES_PASSWORD: "rtf558Ur" #Введите пароль пользователя базы данных
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      poetry run python zit_app.py
      

  postgres:
    hostname: postgres
    restart: always
    image: postgres:latest

    environment:
      POSTGRES_DB: "test_app"  #Введите название базы данных postgres
      POSTGRES_USER: "postgres"  #Введите название пользователя базы данных
      POSTGRES_PASSWORD: "rtf558Ur" #Введите пароль пользователя базы данных
    ports:
      - "5432:5432"
