services:
  web:
    restart: always
    build: .
    links:
      - postgres:postgres

    environment:
      DEBUG: False
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "test_app"
      DATABASE_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rtf558Ur"
      PYTHONPATH: "/ZIT_teat_app/"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      poetry run python app/zit_app.py
      

  postgres:
    hostname: postgres
    restart: always
    image: postgres:latest

    environment:
      POSTGRES_DB: "test_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rtf558Ur"
    ports:
      - "5432:5432"
