name: Pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker compose logs
      - name: Test with pytest
        run: docker exec zit_teat_app-web-1 bash -c "poetry run pytest"
